// import "./fonts/coinbase-mono/stylesheet.css";

import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.scss";
import Header from "@/components/header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const sfPro = localFont({
  src: [
    {
      path: "./fonts/SFPro.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/SFPro-Semibold.ttf",
      weight: "590",
      style: "normal",
    },
    {
      path: "./fonts/SFPro-Medium.ttf",
      weight: "510",
      style: "normal",
    },
    {
      path: "./fonts/SFPro-SemiboldItalic.ttf",
      weight: "590",
      style: "italic",
    },
    {
      path: "./fonts/SFPro-ExpandedBold.ttf",
      weight: "760",
      style: "normal",
    },
  ],
  variable: "--font-sf-pro",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${sfPro.variable}`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
